sudely/urls.py
from django.urls import path, include
from . import views
from .views import ContactFormView, ContactResultView

app_name= 'sudely'

urlpatterns = [
    path('', views.home_view, name='home'),
    path("sudely/", views.GetData.as_view(), name="index"),
    path("netsea/", views.netsea.as_view(), name="netsea"),
    path("zakka/", views.zakka.as_view(), name="zakka"),
    path("logpass/", views.Formidpassview.as_view(), name="logpass"),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(), name="create"),
    path("kawada/", views.kawada.as_view(), name="kawada"),
    path("kenko/", views.kenko.as_view(), name="kenko"),
    path("download/", views.downloader, name="downloader"),
    path("kanri/", views.kanri.as_view(), name="kanri"),
    path('contact/', ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),
    path("log/", views.StatusView.as_view(), name="status"),
    path("exp/", views.expview.as_view(), name="exp"),
]

sudely/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Formidpass(models.Model):
    sudelyid = models.EmailField(blank=True)
    sudelypass = models.CharField(max_length=30, blank=True)
    netseaid = models.EmailField(blank=True)
    netseapass = models.CharField(max_length=30, blank=True)
    zakkaid = models.EmailField(blank=True)
    zakkapass = models.CharField(max_length=30, blank=True)
    kawadaid = models.CharField(max_length=30, blank=True)
    kawadapass = models.CharField(max_length=30, blank=True)
    kenkoid = models.EmailField(blank=True)
    kenkopass = models.CharField(max_length=30, blank=True)
    mwsseller = models.CharField(max_length=30, blank=True)
    authtoken = models.CharField(max_length=100, blank=True)
    rakuapi = models.CharField(max_length=100, blank=True)
    yahooapi = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return str(self.author)

class Request(models.Model):
    image = models.TextField(blank=True, null=True)
    url = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)
    jan = models.TextField(blank=True, null=True)
    moq = models.TextField(blank=True, null=True)
    price = models.TextField(blank=True, null=True)
    tanka = models.TextField(blank=True, null=True)
    asin = models.TextField(blank=True, null=True)
    rank = models.TextField(blank=True, null=True)
    rakuprice = models.TextField(blank=True, null=True)
    rakuurl = models.TextField(blank=True, null=True)
    yahooprice = models.TextField(blank=True, null=True)
    cart = models.TextField(blank=True, null=True)
    low = models.TextField(blank=True, null=True)
    site = models.TextField(blank=True, null=True)
    taskid = models.TextField(blank=True, null=True)
    author = models.TextField(blank=True, null=True)

class Celerytask(models.Model):
    url = models.TextField(blank=True, null=True)
    site = models.TextField(blank=True, null=True)
    taskid = models.TextField(blank=True, null=True)
    taskstatus = models.TextField(blank=True, null=True)
    author = models.TextField(blank=True, null=True)

sudely/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from .models import Formidpass
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse

class RequestForm(forms.Form):
    url = forms.URLField(label="URL")
    pages = forms.IntegerField(initial=1, label="取得ページ数")
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['url'].widget.attrs["class"] = "url_field"

        choice1 = forms.fields.ChoiceField(
            choices=(
                ('rank', 'ランキング'),
                ('rank-', 'ランキング昇順'),
            ),
            required=True,
            widget=forms.widgets.Select
        )


class LoginForm(AuthenticationForm):
    '''ログインフォーム'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class IdPassForm(forms.ModelForm):
    class Meta:
        model = Formidpass
        fields = ("sudelyid", "sudelypass", "netseaid", "netseapass", "zakkaid", "zakkapass",
                  "kawadaid", "kawadapass", "kenkoid", "kenkopass",
                  "mwsseller", "authtoken", "rakuapi", "yahooapi")

class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

sudely/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .forms import RequestForm
from .forms import IdPassForm
from .forms import LoginForm
from .models import Formidpass, Request, Celerytask
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView # 追記
from django.contrib.auth.forms import UserCreationForm  # 追記
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect
from django_celery_results.models import TaskResult
from celery.result import ResultBase
from celery.result import AsyncResult
from celery.result import ResultSet
from django.urls import reverse_lazy # 追記
import datetime
import csv
import io
from django.http import HttpResponse
import pandas as pd
from .tasks import starttask
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from .forms import ContactForm
import os
import environ

env = environ.Env()
env.read_env('.env')


class Formidpassview(generic.FormView):
    template_name = "sudely/idpass.html"
    form_class = IdPassForm
    def form_valid(self, form):
        qryset = form.save(commit=False)
        qryset.author = self.request.user
        try:
            obj = Formidpass.objects.get(author=self.request.user)
            obj.delete()
            qryset.save()
        except:
            qryset.save()
        return redirect("/")

    def get(self, request):

        try:
            dbitem = Formidpass.objects.get(author=self.request.user)
            initial_dict = dict(sudelyid=dbitem.sudelyid, sudelypass=dbitem.sudelypass,\
                                netseaid=dbitem.netseaid, netseapass=dbitem.netseapass,\
                                zakkaid=dbitem.zakkaid, zakkapass=dbitem.zakkapass,
                                kawadaid=dbitem.kawadaid, kawadapass=dbitem.kawadapass,
                                kenkoid=dbitem.kenkoid, kenkopass=dbitem.kenkopass,
                                mwsseller=dbitem.mwsseller, authtoken=dbitem.authtoken,
                                rakuapi=dbitem.rakuapi, yahooapi=dbitem.yahooapi,
                                )

            form = IdPassForm(request.GET or None, initial=initial_dict)
        except:
            form = IdPassForm

        return render(request, "sudely/idpass.html", dict(form=form))

class GetData(LoginRequiredMixin, generic.FormView):
    template_name = "sudely/index.html"
    form_class = RequestForm

    def form_valid(self, form):
        now = datetime.datetime.now()
        url = form.cleaned_data["url"]
        username = str(self.request.user)
        urlpages = form.cleaned_data["pages"]
        dbitem = Formidpass.objects.get(author=self.request.user)
        sudelyid = dbitem.sudelyid
        sudelypass = dbitem.sudelypass
        seller = dbitem.mwsseller
        access = dbitem.authtoken
        rakuapi = dbitem.rakuapi
        yahooapi = dbitem.yahooapi
        sitename = "スーパーデリバリー"
        task = starttask.delay(url, urlpages, sudelyid, sudelypass, seller, access, rakuapi, yahooapi, username, sitename)
        task_id = task.id
        # タスクデータベースに保存
        taskstatus = AsyncResult(task_id).status
        savedb(username, sitename, url, task_id, taskstatus)
        result = Request.objects.filter(author=self.request.user, site=sitename).order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "tasks": task_id,
            "result": result,
            "form": self.form_class,
            "ps": ps,
            }

        now = datetime.datetime.now()
        return render(
            self.request,
            self.template_name,
            context
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = Request.objects.filter(author=self.request.user, site="スーパーデリバリー").order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "result": result,
            "form": self.form_class,
            "ps": ps,
        }
        return context

class netsea(LoginRequiredMixin, generic.FormView):
    template_name = "sudely/netsea.html"
    form_class = RequestForm

    def form_valid(self, form):
        now = datetime.datetime.now()
        url = form.cleaned_data["url"]
        dbitem = Formidpass.objects.get(author=self.request.user)
        netseaid = dbitem.netseaid
        netseapass = dbitem.netseapass
        username = str(self.request.user)
        seller = dbitem.mwsseller
        access = dbitem.authtoken
        rakuapi = dbitem.rakuapi
        yahooapi = dbitem.yahooapi
        pages = form.cleaned_data["pages"]
        task = starttask.delay(url, pages, netseaid, netseapass, seller, access, rakuapi, yahooapi, username, "NETSEA")
        task_id = task.id
        taskstatus = AsyncResult(task_id).status
        sitename = "NETSEA"
        savedb(username, sitename, url, task_id, taskstatus)
        result = Request.objects.filter(author=self.request.user, site="NETSEA").order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "tasks": task_id,
            "result": result,
            "form": self.form_class,
            "ps": ps,
        }

        now = datetime.datetime.now()
        return render(
            self.request,
            self.template_name,
            context
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = Request.objects.filter(author=self.request.user, site="NETSEA").order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "result": result,
            "form": self.form_class,
            "ps": ps,

        }
        return context

class zakka(LoginRequiredMixin, generic.FormView):
    template_name = "sudely/zakka.html"
    form_class = RequestForm

    def form_valid(self, form):
        now = datetime.datetime.now()
        url = form.cleaned_data["url"]
        username = str(self.request.user)
        dbitem = Formidpass.objects.get(author=self.request.user)
        zakkaid = dbitem.zakkaid
        zakkapass = dbitem.zakkapass
        pages = form.cleaned_data["pages"]
        seller = dbitem.mwsseller
        access = dbitem.authtoken
        rakuapi = dbitem.rakuapi
        yahooapi = dbitem.yahooapi
        task = starttask.delay(url, pages, zakkaid, zakkapass, seller, access, rakuapi, yahooapi, username, "ザッカネット")
        task_id = task.id
        taskstatus = AsyncResult(task_id).status
        sitename = "ザッカネット"
        savedb(username, sitename, url, task_id, taskstatus)
        result = Request.objects.filter(author=self.request.user, site="ザッカネット").order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "tasks": task_id,
            "result": result,
            "form": self.form_class,
            "ps": ps,
        }

        now = datetime.datetime.now()
        return render(
            self.request,
            self.template_name,
            context
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = Request.objects.filter(author=self.request.user, site="ザッカネット").order_by("-id").all().distinct()
        paginator = Paginator(result, 100)
        p = self.request.GET.get('p', 1)
        try:
            ps = paginator.get_page(p)
        except PageNotAnInteger:
            ps = paginator.get_page(1)
        except EmptyPage:
            ps = paginator.get_page(1)
        context = {
            "result": result,
            "form": self.form_class,
            "ps": ps,
        }
        return context


class kawada(LoginRequiredMixin, generic.FormView):
    template_name = "sudely/kawada.html"
    form_class = RequestForm

    def form_valid(self, form):
        now = datetime.datetime.now()
        url = form.cleaned_data["url"]
        pages = form.cleaned_data["pages"]
        username = str(self.request.user)
        dbitem = Formidpass.objects.get(author=self.request.user)
        kawadaid = dbitem.kawadaid
        kawadapass = dbitem.kawadapass
        seller = dbitem.mwsseller
        access = dbitem.authtoken
        rakuapi = dbitem.rakuapi
        yahooapi = dbitem.yahooapi
        task = starttask.delay(url, pages, kawadaid, kawadapass, seller, access, rakuapi, yahooapi, username, "カワダ")
        task_id = task.id
        taskstatus = AsyncResult(task_id).status
        sitename = "カワダ"
        savedb(username, sitename, url, task_id, taskstatus)

sudely/templates/sudely/header.html
{% load static %}
{% load widget_tweaks %}

  <head>
      <link rel="icon" type="image/png" href="{% static '/icon/favicon.png' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
      <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <script src="https://unpkg.com/ionicons@4.1.2/dist/ionicons.js"></script>
  </head>

  <body>

    <div id="my-spinner" class="box loaded">
      <div class="spinner type1">
        <span>Loading...</span>
      </div>
    </div>


    <div class="header-box">
        <div class="top-area">
            <span class="click-area">
                <a href="/sudely/" class="linkcolor">SuperDelivery</a>
            </span>
            <span class="click-area">
                <a href="/netsea/" class="linkcolor">NETSEA</a>
            </span>
            <span class="click-area">
                <a href="/zakka/" class="linkcolor">ザッカネット</a>
            </span>
            <span class="click-area">
                  <a href="/kawada/" class="linkcolor">カワダオンライン</a>
            </span>
            <span class="click-area">
                  <a href="/kenko/" class="linkcolor">Kenko卸</a>
            </span>
            <!--
            <span class="click-area">
                  <a href="/kanri/" class="linkcolor">管理画面</a>
            </span>
            -->
            <span class="click-area">
                <a href="/log/" class="linkcolor">ログ</a>
          </span>

            <span class="click-area">
                  <a href="/contact/" class="linkcolor">お問い合わせ</a>
            </span>
            <span class="click-area">
                  <a href="/exp/" class="linkcolor">使い方</a>
            </span>

            {% if user.is_authenticated %}
            <span class="log-area">
                <ion-icon name="person" style="vertical-align: middle;"></ion-icon><a class="user-link">{{ user.get_username }}　</a>

                <a class="nav-link" href="{% url 'sudely:logpass' %}">
                    <ion-icon name="globe" style="vertical-align: middle;"></ion-icon>ログイン情報編集　</a>

                <a class="nav-link" href="{% url 'sudely:logout' %}">
                    <ion-icon name="log-out" style="vertical-align: middle;"></ion-icon>ログアウト</a>
            </span>
            {% endif %}
        </div>
    </div>


          {% block content %}

          {% endblock %}

      <p>{{result2}}</p>

    {% for res in ps %}
    <div class="text-box">
        <a href="{{res.url}}" target="_blank"><p class="title">{{res.title}}</p></a>
        <p>
        <a href="{{res.url}}" target="_blank"><img src={{res.image}} align="left" width="180" height="180" hspace="15"  border="1"></a>
        <p class="price">商品単価：{{res.tanka}}</p>
        Amazon最安値 ：{{res.low}}円　Amazonカート :{{res.cart}}円
        <br>
        楽天最安値:{{res.rakuprice}}円　ヤフー最安値:{{res.yahooprice}}円
        <br>
        ランキング :{{res.rank}}位
        <br>
        支払総額：{{res.price}}
        <br>
        種    類：{{res.moq}}
        <br>
        JANコード：{{res.jan}}
        <!--
        <div class="block">
          <button type="button" class="amazon_button" onclick=location.href='https://www.amazon.co.jp/s?k={{res.jan}}&tag=amakahi01-22'">Amazonで検索</button>
        <br>
            <button type="button" class="rakuten_button" onclick=location.href='https://www.amazon.co.jp/s?k={{res.jan}}&tag=amakahi01-22'">楽天で検索</button>
        </div>
        -->
        </p>
    </div>
    {% endfor %}

    <!-- 前のページへのリンク -->
    {% if ps.has_previous %}
        <a href="?p={{ ps.previous_page_number }}">前へ</a>
    {% endif %}

    {% if ps.has_previous %}
        {% if ps.previous_page_number != 1 %}
            <li><a class="page-link text-primary d-inline-block" href="?p=1">1</a></li>
            <li>…</li>
        {% endif %}
        <li><a class="page-link text-primary d-inline-block" href="?p={{ ps.previous_page_number }}">{{ ps.previous_page_number }}</a></li>
    {% endif %}

    <!-- 現在のページ番号と全体のページ数 -->
    <span>
        {{ ps.number }} / {{ ps.paginator.num_pages }}
    </span>

    {% if ps.has_next %}
        <li><a class="page-link text-primary d-inline-block" href="?p={{ ps.next_page_number }}">{{ ps.next_page_number }}</a></li>
        {% if ps.next_page_number != ps.paginator.num_pages %}
            <li>…</li>
            <li><a class="page-link text-primary d-inline-block" href="?p={{ ps.paginator.num_pages }}">{{ ps.paginator.num_pages }}</a></li>
        {% endif %}
    {% endif %}

    <!-- 次のページへのリンク -->
    {% if ps.has_next %}
        <a href="?p={{ ps.next_page_number }}">次へ</a>
    {% endif %}


  </body>

sudely/templates/sudely/index.html
{% extends "sudely/header.html" %}


{% block content %}
{% load widget_tweaks %}

<div class="container">
    <div class = "topma">
    <div class="mat-elevation-z8">
          <span class="title-area">
              <a href="https://www.superdelivery.com/" target="_blank">SuperDelivery</a>
          </span>
    </div>
    </div>
    <div class="mat">
        <div class="form-box">
            <form action="/sudely/" method="POST" name="button">
                SuperDelivery
                <br>
                <b>URL:</b>{{form.url|add_class:"form-field"}}
                <b>取得ページ数:</b>{{form.pages|add_class:"form-field"}}
                {% csrf_token %}
                <button type="submit" class="button" onclick="OnButtonClick();">Request</button>
                <a href="{% url 'sudely:downloader' %}">ダウンロード</a>
            </form>
        </div>
    <br>
    <hr>

    </div>
</div>

{% endblock %}

sudely/templates/sudely/kawada.html
{% extends "sudely/header.html" %}
{% block content %}
{% load widget_tweaks %}

<div class="container">
    <div class = "topma">
    <div class="mat-elevation-z8">
          <span class="title-area">
              <a href="https://ganguoroshi.jp/" target="_blank">カワダオンライン</a>
          </span>
    </div>
    </div>
    <div class="mat">
        <div class="form-box">
            <form action="/kawada/" method="POST" name="button">
                カワダオンライン
                <br>
                <b>URL:</b>{{form.url|add_class:"form-field"}}
                <b>取得ページ数:</b>{{form.pages|add_class:"form-field"}}
                {% csrf_token %}
                <button type="submit" class="button" onclick="OnButtonClick();">Request</button>
                <a href="{% url 'sudely:downloader' %}">ダウンロード</a>
            </form>
        </div>
    <br>
    <hr>
    </div>
</div>


{% endblock %}

sudely/templates/sudely/kenko.html
{% extends "sudely/header.html" %}

{% block content %}
{% load widget_tweaks %}

<div class="container">
    <div class = "topma">
    <div class="mat-elevation-z8">
          <span class="title-area">
              <a href="https://www1.kenko064.com/" target="_blank">kenko卸</a>
          </span>
    </div>
    </div>
    <div class="mat">
        <div class="form-box">
            <form action="/kenko/" method="POST" name="button">
                Kenko卸
                <br>
                <b>URL:</b>{{form.url|add_class:"form-field"}}
                <b>取得ページ数:</b>{{form.pages|add_class:"form-field"}}
                {% csrf_token %}
                <button type="submit" class="button" onclick="OnButtonClick();">Request</button>
                <a href="{% url 'sudely:downloader' %}">ダウンロード</a>
            </form>
        </div>
    <br>
    <hr>
    </div>
</div>


{% endblock %}

sudely/templates/sudely/netsea.html
{% extends "sudely/header.html" %}

{% block content %}
{% load widget_tweaks %}


<div class="container">
    <div class = "topma">
    <div class="mat-elevation-z8">
          <span class="title-area">
              <a href="https://www.netsea.jp/" target="_blank">NETSEA</a>
          </span>
    </div>
    </div>
    <div class="mat">
        <div class="form-box">
             <form action="/netsea/" method="POST" name="button">
                 NETSEA
                 <br>
                <b>URL:</b>{{form.url|add_class:"form-field"}}
                <b>取得ページ数:</b>{{form.pages|add_class:"form-field"}}
                {% csrf_token %}
                <button type="submit" class="button" onclick="OnButtonClick();">Request</button>
                 <a href="{% url 'sudely:downloader' %}">ダウンロード</a>
            </form>
        </div>
    <br>
    <hr>
    </div>
</div>


{% endblock %}

sudely/templates/sudely/status.html
{% load static %}
{% load widget_tweaks %}

<head>
    <link rel="icon" type="image/png" href="{% static '/icon/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <script src="https://unpkg.com/ionicons@4.1.2/dist/ionicons.js"></script>
</head>


<div style="background-color:#3f51b5;font-weight: 800;">    
    <span class="click-area">
        <a href="/sudely/" class="linkcolor">SuperDelivery</a>
    </span>
    <span class="click-area">
        <a href="/netsea/" class="linkcolor">NETSEA</a>
    </span>
    <span class="click-area">
        <a href="/zakka/" class="linkcolor">ザッカネット</a>
    </span>
    <span class="click-area">
        <a href="/kawada/" class="linkcolor">カワダオンライン</a>
    </span>
    <span class="click-area">
        <a href="/kenko/" class="linkcolor">Kenko卸</a>
    </span>
    <span class="click-area">
        <a href="/log/" class="linkcolor">ログ</a>
    </span>

    <span class="click-area">
        <a href="/contact/" class="linkcolor">お問い合わせ</a>
    </span>
    <span class="click-area">
        <a href="/exp/" class="linkcolor">使い方</a>
    </span>


    {% if user.is_authenticated %}
    <span class="log-area2">
        <ion-icon name="person" style="vertical-align: middle;"></ion-icon><a class="user-link">{{ user.get_username }}</a>

        <a class="nav-link" href="{% url 'sudely:logpass' %}">
            <ion-icon name="globe" style="vertical-align: middle;"></ion-icon>ログイン情報編集　</a>

        <a class="nav-link" href="{% url 'sudely:logout' %}">
            <ion-icon name="log-out" style="vertical-align: middle;"></ion-icon>ログアウト</a>
    </span>
    {% endif %}

</div>
    
    <table>
        <thead>
            <td><label><input type="checkbox" id="all" class="checkbox-input"></label></td>
            <td>サイト名</td>
            <td>商品ページ</td>
            <td>状態</td>
        </thead>
        <tbody>
        {% for res in result %}        
            <tr class="text-box">
                <td class="text-valign-middle" width="5%"><label><input type="checkbox" name="delete" class="checkbox-input" value="{{ res.id }}" id="boxes"></label></td>
                <td class="text-valign-middle" width="15%"><p class="price"></p>{{res.site}}</td>
                
                <td class="text-valign-middle" width="10%"><a href="{{res.url}}" class="linkcolor2">{{res.url}}</a></td>    
                {% if res.taskstatus == "SUCCESS" %}     
                <td class="text-valign-middle" width="10%"><p class="price"></p>取得完了</td>
                {% elif res.taskstatus == "FAILURE" %}
                <td class="text-valign-middle" width="10%"><p class="price"></p>エラー</td>
                
                {% endif %}            
            </tr>
        {% endfor %}            
        </tbody>
    </table>
    <p class="price">確認</p>

sudely/templates/sudely/zakka.html
{% extends "sudely/header.html" %}


{% block content %}
{% load widget_tweaks %}

<div class="container">
    <div class = "topma">
    <div class="mat-elevation-z8">
          <span class="title-area">
              <a href="https://www.zakka.net/" target="_blank">ザッカネット</a>
          </span>
    </div>
    </div>
    <div class="mat">
        <div class="form-box">
            <form action="/zakka/" method="POST" name="button">
                ザッカネット
                <br>
                <b>URL:</b>{{form.url|add_class:"form-field"}}
                <b>取得ページ数:</b>{{form.pages|add_class:"form-field"}}
                {% csrf_token %}
                <button type="submit" class="button" onclick="OnButtonClick();">Request</button>
                <a href="{% url 'sudely:downloader' %}">ダウンロード</a>
            </form>
        </div>
    <br>
    <hr>

    </div>
</div>

{% endblock %}